## Redes Neurais e Aprendizado Profundo

#### Perceptron em Pytorch
#### - Regressão
#### - Forward pass
#### - Treinamento com Backpropagation/Gradient Descent


Moacir A Ponti - 2022

In [ ]:
import torch
import numpy as np

In [ ]:
class Perceptron():
  
    def __init__(self, num_inputs, lr=0.01):
      self.w = torch.normal(0,1, (num_inputs,1), requires_grad=True)
      self.b = torch.zeros(1, requires_grad=True)
      self.num_inputs = num_inputs
      self.lr = lr

    def activation_relu(self, x):
      a = torch.zeros_like(x)
      return torch.max(x, a)
    
    def forward(self, X):
      linear = X@self.w + self.b
      return self.activation_relu(linear)

    def squared_loss(self, y, y_hat):
      l = (y.reshape(y_hat.shape) - y_hat)**2
      return l.mean()

    def backward(self, X, y):
      y_hat = self.forward(X) # forward pass
      errors = (y.reshape(y_hat.shape) - y_hat) # differentiate
      return errors

    def train_step(self, X, y):
      for i in range(y.shape[0]):
        error = self.backward(X[i].reshape(1, self.num_inputs), y[i]).reshape(-1)
        # gradient descent
        self.w = self.w + self.lr*(error*X[i]).reshape(self.num_inputs,1)
        self.b = self.b + self.lr*error


In [ ]:
model = Perceptron(3, lr=0.002)
model.w, model.b, model.lr

(tensor([[-0.0549],
         [ 1.1521],
         [ 0.0850]], requires_grad=True),
 tensor([0.], requires_grad=True),
 0.002)

In [ ]:
# X : 3 dimensoes por instancia
X = torch.arange(30, dtype=torch.float32).reshape((10,3)) + torch.normal(0, 2, (10,3))
print(X)
y = torch.arange(10, dtype=torch.float32)
print(y)

tensor([[ 0.1375, -0.3193,  1.4472],
        [ 3.4927,  0.9926,  7.5517],
        [ 5.5432,  5.2225,  7.3877],
        [13.0063, 13.8235, 10.6459],
        [12.2655, 13.7464,  9.5232],
        [12.6202, 15.0687, 20.2580],
        [19.0621, 19.7397, 20.9215],
        [20.7848, 20.2596, 25.4952],
        [22.3901, 23.9016, 27.7338],
        [25.7819, 30.7584, 30.1549]])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
model.forward(X),  y

(tensor([[ 0.0000],
         [ 1.5935],
         [ 6.3405],
         [16.1172],
         [15.9737],
         [18.3897],
         [23.4741],
         [24.3672],
         [28.6653],
         [36.5848]], grad_fn=<MaximumBackward0>),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
model.squared_loss(y, model.forward(X))

tensor(230.8841, grad_fn=<MeanBackward0>)

In [ ]:
model.train_step(X, y)
print('Parameters:', model.w, model.b)
print('Squared Loss:', model.squared_loss(y, model.forward(X)))

Parameters: tensor([[-0.7926],
        [ 1.0266],
        [ 0.3599]], grad_fn=<AddBackward0>) tensor([-0.0278], grad_fn=<AddBackward0>)
Squared Loss: tensor(20.6231, grad_fn=<MeanBackward0>)


In [ ]:
epochs = 100
for e in range(epochs):
  model.train_step(X, y)
  if e % 20 == 0:
    print(f'Epoch: {e}')
    print('Parameters:', model.w.detach().numpy(), model.b.item())
    print(f'Squared Loss: {model.squared_loss(y, model.forward(X)).item():.6f}')

Epoch: 0
Parameters: [[-0.33239046]
 [ 0.9138653 ]
 [-0.14526576]] -0.02955181710422039
Squared Loss: 7.774010
Epoch: 20
Parameters: [[-0.6971568 ]
 [ 0.7889745 ]
 [-0.04901513]] -0.07609856873750687
Squared Loss: 14.832491
Epoch: 40
Parameters: [[-0.55963314]
 [ 0.64953756]
 [-0.02716886]] 0.052946191281080246
Squared Loss: 12.579431
Epoch: 60
Parameters: [[-0.42734832]
 [ 0.51906174]
 [-0.00488682]] 0.16958719491958618
Squared Loss: 10.065763
Epoch: 80
Parameters: [[-0.3011292 ]
 [ 0.39930713]
 [ 0.0180102 ]] 0.2718864679336548
Squared Loss: 7.402274


In [ ]:
model.forward(X),  y

(tensor([[0.2972],
         [0.5364],
         [1.6211],
         [3.4665],
         [3.5012],
         [4.5678],
         [5.0760],
         [5.2361],
         [6.3479],
         [8.2627]], grad_fn=<MaximumBackward0>),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
X_t = torch.arange(15, dtype=torch.float32).reshape((5,3)) + torch.normal(0, 3, (5,3))
print(X_t)
y_t = torch.arange(5, dtype=torch.float32)
print(y_t)

tensor([[-1.0989,  0.3473, -0.3783],
        [ 5.7723,  3.5411,  3.8471],
        [ 6.3507,  4.9092, 15.2436],
        [ 8.9827,  8.8932, 11.1259],
        [13.8262, 14.7092, 13.9638]])
tensor([0., 1., 2., 3., 4.])


In [ ]:
model.forward(X_t),  y_t

(tensor([[0.6325],
         [0.7781],
         [1.8623],
         [2.5107],
         [3.8345]], grad_fn=<MaximumBackward0>), tensor([0., 1., 2., 3., 4.]))

In [ ]:
model.squared_loss(y_t, model.forward(X_t))

tensor(0.1470, grad_fn=<MeanBackward0>)