## Redes Neurais e Aprendizado Profundo

#### Bonus: Autograd em pytorch


Moacir A Ponti - 2022

In [ ]:
import torch
from torch.autograd import grad
import torch.nn.functional as F

In [ ]:
x = torch.tensor([5.])
w = torch.tensor([1.2], requires_grad=True)
b = torch.tensor([0.5], requires_grad=True)

act = F.relu(x*w + b)
print(act)

tensor([6.5000], grad_fn=<ReluBackward0>)


In [ ]:
grad(act, b, retain_graph=True)

(tensor([1.]),)

In [ ]:
grad(act, w)

(tensor([5.]),)

In [ ]:
grad(act, w)

RuntimeError: ignored