## Redes Neurais e Aprendizado Profundo

#### Introdução a pytorch

Moacir A Ponti - 2022

In [ ]:
import torch
import numpy as np

Operações similares à `numpy` para geração de arrays/matrizes

In [ ]:
np.arange(5) # 0 a 4

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,10) # 1 a 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.ones((3,10))*5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

Tensores
* geração
* tamanho
* alteração de formato
* indexação e fatiamento

In [ ]:
A = torch.arange(1,10)

In [ ]:
B = torch.ones((2,5))

In [ ]:
A.shape[0]

9

In [ ]:
A.numel()

9

In [ ]:
B.numel()

10

In [ ]:
B.shape

torch.Size([2, 5])

In [ ]:
B.shape[1]

5

In [ ]:
# chamo o método reshape, que altera o formato e RETORNA um novo tensor
# com o novo formato
print(A.reshape((3,3)))
print(A.reshape((3,3)).shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [ ]:
A[0]

tensor(1)

In [ ]:
A[-1]

tensor(9)

In [ ]:
A[0:4]

tensor([1, 2, 3, 4])

In [ ]:
A[:-2]

tensor([1, 2, 3, 4, 5, 6, 7])

Operações básicas e funções
* unárias
* binárias elemento-a-elemento
* lógicas
* concatenação 
* broadcasting: operacoes em tensores/array de formatos diferentes, expandindo as dimensoes de um deles

In [ ]:
A.dtype

torch.int64

In [ ]:
C = torch.arange(1,11, dtype=torch.float32)
print(C.dtype)
print(C)

torch.float32
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [ ]:
# operadores unarios
print(torch.log(C))
print(torch.exp(C))

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794, 2.1972,
        2.3026])
tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])


In [ ]:
D = torch.ones(10)*3
print(D)

tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])


In [ ]:
# operadores binários - ponto a ponto (elemento a elemento)
# soma, subtracao, mult, div, exponenciacao
C + D, C - D, C * D, C / D, C ** D

(tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.]),
 tensor([-2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]),
 tensor([0.3333, 0.6667, 1.0000, 1.3333, 1.6667, 2.0000, 2.3333, 2.6667, 3.0000,
         3.3333]),
 tensor([   1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729., 1000.]))

In [ ]:
E = torch.arange(10,100,5)
print(E)

tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])


In [ ]:
E > 50

tensor([False, False, False, False, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
C > D

tensor([False, False, False,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
print(C)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [ ]:
C[C > D]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
mascara_binaria = torch.tensor([True]*2 + [False]*4 + [True]*4)

In [ ]:
C[mascara_binaria]

tensor([ 1.,  2.,  7.,  8.,  9., 10.])

In [ ]:
# broadcasting
x = torch.arange(4).reshape(4,1)
y = torch.arange(2).reshape(1,2)

x,y

(tensor([[0],
         [1],
         [2],
         [3]]), tensor([[0, 1]]))

In [ ]:
# broadcasting expandiu as dimensoes da matriz x ao longo das colunas
#  e da matriz y ao longo das linhas antes de realizar a soma
x+y

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
x_B = torch.tensor([[0, 0], [1, 1], [2, 2], [3, 3]])
y_B = torch.tensor([[0, 1], [0, 1], [0, 1], [0, 1]])
x_B+y_B

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
x_B.shape, y.shape

(torch.Size([4, 2]), torch.Size([1, 2]))

In [ ]:
x_B + y 

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

Cópias de tensores
* cópia rasa (reuso de memória)
* cópia profunda

In [ ]:
C = torch.arange(1,11, dtype=torch.float32)

id_antes = id(C)
C = C + D # cria uma nova variavel/espaco na memoria

id(C) == id_antes

False

In [ ]:
C = torch.arange(1,11, dtype=torch.float32)

id_antes = id(C)
C[:] = C + D # reusa a memória

id(C) == id_antes

True

In [ ]:
# copia rasa
id_antes = id(C)
D = C # D é uma "visao/view" de C
id(D) == id_antes

True

In [ ]:
# copia profunda
id_antes = id(C)
D = C.clone() # clona C e cria nova variavel D
id(D) == id_antes

False

Vetores e Matrizes
* definições
* aritmética de tensores
* redução (calcular algo ao longo de dimensoes do tensor)
* produto interno
* matriz-vetor
* matriz-matriz
* norma

In [ ]:
x = torch.arange(5, dtype=torch.float64)
A = torch.arange(25, dtype=torch.float64).reshape((5,5))
x, A

(tensor([0., 1., 2., 3., 4.], dtype=torch.float64),
 tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.]], dtype=torch.float64))

In [ ]:
# transpor matriz/vetor
A.T

tensor([[ 0.,  5., 10., 15., 20.],
        [ 1.,  6., 11., 16., 21.],
        [ 2.,  7., 12., 17., 22.],
        [ 3.,  8., 13., 18., 23.],
        [ 4.,  9., 14., 19., 24.]], dtype=torch.float64)

In [ ]:
x.shape

torch.Size([5])

In [ ]:
x

tensor([0, 1, 2, 3, 4])

In [ ]:
x.reshape((1,5))

tensor([[0, 1, 2, 3, 4]])

In [ ]:
x.reshape((1,5)).shape

torch.Size([1, 5])

In [ ]:
x.reshape((1,5)).T

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [ ]:
# reducao
print(A)
A.sum()

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


tensor(300)

In [ ]:
A.sum(axis=0)

tensor([50, 55, 60, 65, 70])

In [ ]:
A.sum(axis=1)

tensor([ 10,  35,  60,  85, 110])

In [ ]:
A.mean(axis=1)

tensor([ 2.,  7., 12., 17., 22.], dtype=torch.float64)

In [ ]:
A.sum() / A.numel()

tensor(12., dtype=torch.float64)

Produto interno

$\mathbf{x}^T\mathbf{y} = \sum_i x_i y_i$ 

In [ ]:
# produto interno

In [ ]:
a = torch.arange(1,6, dtype=torch.float32)
b = torch.ones(5)*3
a,b

(tensor([1., 2., 3., 4., 5.]), tensor([3., 3., 3., 3., 3.]))

In [ ]:
torch.dot(a,b)

tensor(45.)

In [ ]:
### multiplicacao matriz - vetor

In [ ]:
A, x, torch.mv(A,x)

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24.]], dtype=torch.float64),
 tensor([0., 1., 2., 3., 4.], dtype=torch.float64),
 tensor([ 30.,  80., 130., 180., 230.], dtype=torch.float64))

In [ ]:
A@x

tensor([ 30.,  80., 130., 180., 230.], dtype=torch.float64)

In [ ]:
torch.mm(A,A)

tensor([[ 150.,  160.,  170.,  180.,  190.],
        [ 400.,  435.,  470.,  505.,  540.],
        [ 650.,  710.,  770.,  830.,  890.],
        [ 900.,  985., 1070., 1155., 1240.],
        [1150., 1260., 1370., 1480., 1590.]], dtype=torch.float64)

In [ ]:
A@A

tensor([[ 150.,  160.,  170.,  180.,  190.],
        [ 400.,  435.,  470.,  505.,  540.],
        [ 650.,  710.,  770.,  830.,  890.],
        [ 900.,  985., 1070., 1155., 1240.],
        [1150., 1260., 1370., 1480., 1590.]], dtype=torch.float64)

In [ ]:
A@y

RuntimeError: ignored

In [ ]:
# norma de um tensor - norma Euclidiana ou norma L2
# raiz quadrada da soma dos quadrados
# exp. com 2 elementos: sqrt(x_1^2 + x_2^2)

In [ ]:
x

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [ ]:
torch.norm(x)

tensor(5.4772, dtype=torch.float64)