## Redes Neurais e Aprendizado Profundo

#### Modelo linear em Pytorch

Moacir A Ponti - 2022

In [ ]:
import torch
from torch.utils.data import DataLoader

In [ ]:
class Model():

    # construtor inicializa os parametros
    def __init__(self, num_inputs):
      # w - amostrando de uma distribuicao normal media 0 e desvio padrao 1
      self.w = torch.normal(0, 1, (num_inputs, 1), requires_grad=True)
      # b - com valor constante 1 ou 0 ou as vezes 1/total de classes
      self.b = torch.zeros(1, requires_grad=True)
   
    # forward -> processa uma entrada X até a saída
    def forward(self, X):
      # linear(Xw + b)
      return X@self.w + self.b

    def loss(self, y, y_hat):
      # perda quadratica
      l = (y_hat - y.reshape(y_hat.shape))**2 / 2 
      return l.mean()


In [ ]:
# modelo linear 
my_model = Model(2)

In [ ]:
my_model.w, my_model.b

(tensor([[0.7353],
         [0.8808]], requires_grad=True), tensor([0.], requires_grad=True))

In [ ]:
my_model.forward(torch.tensor([[1,1]], dtype=torch.float32))

tensor([[2.6366]])

In [ ]:
# regressao
X = torch.arange(16, dtype=torch.float32).reshape((8,2)) + torch.normal(0,0.5, (8,2))
y = torch.arange(8, dtype=torch.float32)
X, y 

(tensor([[ 0.4577,  1.0293],
         [ 2.0885,  3.6218],
         [ 4.3514,  4.2855],
         [ 5.2740,  6.8023],
         [ 7.1706,  8.1242],
         [10.4427, 11.6639],
         [11.5103, 13.1557],
         [14.2401, 14.4406]]), tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
my_model.forward(X), y

(tensor([[ 1.2431],
         [ 4.7256],
         [ 6.9740],
         [ 9.8691],
         [12.4279],
         [17.9514],
         [20.0502],
         [23.1891]], grad_fn=<AddBackward0>),
 tensor([0., 1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
y_hat = my_model.forward(X)
## loss!!!
my_model.loss(y, y_hat)

tensor(49.1009, grad_fn=<MeanBackward0>)